version: '3'
services:
  mysql:
    image: 'mysql:5.7'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=Dia$$514080
      - MYSQL_DATABASE=mobile_e_shop
    ports:
      - "3307:3306"
  eshop:
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/mobile_e_shop?createDatabaseIfNotExist=true&useUnicode=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Dia$$514080
    build: .
    depends_on:
      - mysql
